spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/peachub
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com.peachub.app: DEBUG
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG