spring.application.name=PeacHub

spring.datasource.url=jdbc:postgresql://localhost:5432/peachub
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

genius.token=LW9nJtaqrFyRKUvnJtHbbEb5C2mwFPW60OjyJB48WD5XvWE112CNAzHFCWPd_QMi